# Generated by Django 3.2.9 on 2022-02-13 06:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('id_cpopula', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=16)),
                ('provincia', models.CharField(max_length=50)),
                ('habitantes', models.IntegerField()),
                ('viviendas', models.IntegerField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Consejos Populares',
                'ordering': ['provincia'],
            },
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investigators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('municipio', models.CharField(max_length=38)),
                ('codigo', models.FloatField(max_length=5)),
                ('provincia', models.CharField(max_length=38)),
                ('closed', models.CharField(max_length=3)),
                ('area', models.FloatField()),
                ('areanew', models.FloatField()),
                ('arear', models.FloatField()),
                ('the_geom2', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('provincia', models.CharField(max_length=38)),
                ('codigo', models.IntegerField()),
                ('dtrepresen', models.CharField(max_length=254)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('date_time', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_public', models.CharField(choices=[('PUBLIC', 'PÚBLICO'), ('PRIVATE', 'PRIVADO')], max_length=7)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workStation.investigator')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ['name'],
            },
        ),
    ]
