# Generated by Django 3.2.9 on 2022-05-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0004_investigator_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='image',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
