# Generated by Django 3.2.9 on 2022-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0006_auto_20220513_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='facebook',
            field=models.CharField(default='https://facebook.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='instagram',
            field=models.CharField(default='https://instagram.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='linkedin',
            field=models.CharField(default='https://linkedin.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='twitter',
            field=models.CharField(default='https://twitter.com/', max_length=200),
        ),
    ]
