# Generated by Django 3.2.9 on 2022-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0007_auto_20220513_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigator',
            name='facebook',
            field=models.URLField(default='https://facebook.com/'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='instagram',
            field=models.URLField(default='https://instagram.com/'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='twitter',
            field=models.URLField(default='https://twitter.com/'),
        ),
    ]
