# Generated by Django 3.2.9 on 2022-05-28 03:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0008_auto_20220513_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(default='', max_length=20)),
                ('zone_layer', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Zone names',
                'ordering': ['zone_name'],
            },
        ),
        migrations.AddField(
            model_name='study',
            name='zone_layer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='workStation.zone'),
            preserve_default=False,
        ),
    ]
