# Generated by Django 3.2.9 on 2022-05-31 05:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0010_auto_20220528_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolyLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('layer', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Poly Layers',
            },
        ),
        migrations.RemoveField(
            model_name='study',
            name='zone_layer',
        ),
        migrations.AlterField(
            model_name='study',
            name='zone',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
