# Generated by Django 3.2.9 on 2022-06-02 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0011_auto_20220531_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='zone',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
