# Generated by Django 3.2.9 on 2022-06-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0012_alter_study_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='municipality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='town',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
