# Generated by Django 3.2.9 on 2022-06-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0013_auto_20220602_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolyLayer',
        ),
    ]
