# Generated by Django 3.2.9 on 2022-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0016_auto_20220608_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejopopular',
            name='municipio',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipio',
            name='border_wid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='sup_distkm',
            field=models.FloatField(),
        ),
    ]
