# Generated by Django 3.2.9 on 2022-06-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0017_auto_20220608_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
