# Generated by Django 3.2.9 on 2022-06-14 02:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0018_delete_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_public',
            field=models.CharField(choices=[('PUBLIC', 'PÚBLICO'), ('PRIVATE', 'PRIVADO')], max_length=7, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='study',
            name='zone',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Zona'),
        ),
    ]
