# Generated by Django 3.2.9 on 2022-06-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0020_evidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
