# Generated by Django 3.2.9 on 2022-06-18 00:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0021_delete_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nombre')),
                ('help', models.CharField(max_length=50, null=True, verbose_name='Geolocalizacion')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Punto')),
                ('image', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workStation.study')),
            ],
            options={
                'verbose_name_plural': 'Evidences',
                'ordering': ['name'],
            },
        ),
    ]
