# Generated by Django 3.2.9 on 2022-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0022_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='help',
            field=models.CharField(default='', max_length=500, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='help',
            field=models.CharField(max_length=100, null=True, verbose_name='Geolocalizacion'),
        ),
    ]
