# Generated by Django 3.2.9 on 2022-06-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0023_auto_20220618_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Desconocido', max_length=50, verbose_name='Encabezado')),
            ],
            options={
                'verbose_name_plural': 'Titles',
                'ordering': ['header'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workStation.title'),
        ),
    ]
