# Generated by Django 3.2.9 on 2022-06-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0024_auto_20220622_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workStation.title'),
        ),
    ]
