# Generated by Django 3.2.9 on 2022-08-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0026_alter_study_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
