# Generated by Django 3.2.9 on 2022-08-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0027_auto_20220810_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='date_time',
        ),
    ]
