# Generated by Django 3.2.9 on 2022-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0029_displacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/geometrias/'),
        ),
    ]
