# Generated by Django 3.2.9 on 2022-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workStation', '0030_auto_20220902_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='geometrias/'),
        ),
    ]
